dirtroad69/DirtRoad69/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('face.urls')),
    url(r'^face/', include('face.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dirtroad69/face/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required, permission_required
app_name = 'face'

urlpatterns = [

    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^img/$', views.classification, name='classify'),
    url(r'^retrain/$', views.retrain, name='retrain'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<pk>[0-9])/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'cow/add/$', views.CowCreate.as_view(), name='cow-add'),
   # url(r'cow/get/$', login_required(views.ClassifyView.as_view()), name='classify'),
    url(r'cow/(?P<pk>[0-9])/$', views.CowUpdate.as_view(), name='cow-update'),
    url(r'cow/(?P<pk>[0-9])/delete/$', views.CowDelete.as_view(), name='cow-delete')
]

dirtroad69/face/models.py
from django.db import models
from django.core.urlresolvers import reverse



class Cow(models.Model):
    MALE = 'male'
    FEMALE = 'female'
    JERSEY = 'Jersey'
    AUBRAC = 'Aubrac'
    T1 = 'Horned In Both Sexes'
    T2 = 'Male Only Horned '
    HORN_CHOICES = (
        (T1, 'Horned In Both Sexes'),
        (T2, 'Male Only Horned '),
        )
    GENDER_CHOICES = (
        (MALE, 'male'),
        (FEMALE, 'female'),
        )
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES,
        default=FEMALE)
    BREED_CHOICES = (
        (JERSEY, 'Jersey'),
        (AUBRAC, 'Aubrac'),
        )
    breed = models.CharField(max_length=15, choices=BREED_CHOICES,
        default=JERSEY)
    coat_color = models.CharField(max_length=100, default=None)

    horn_status = models.CharField(max_length=50, choices=HORN_CHOICES,
        default=T1)

    used_for = models.CharField(max_length=100, default=None)
    cow_img = models.FileField(default=None)

    def get_absolute_url(self):
        return reverse('face:detail', kwargs={'pk':self.pk})

    def is_upperclass(self):
        return self.gender in (self.MALE, self.FEMALE)

    def __str__(self):
        return self.name +" - "+" "+self.breed


class Cattle_Retrain(models.Model):
    cow = models.ForeignKey(Cow, on_delete=models.CASCADE)
    cow_video_1 = models.FileField(default=None)
    cow_video_2 = models.FileField(default=None)
    cow_video_3 = models.FileField(default=None)
    cow_video_4 = models.FileField(default=None)

   # def get_absolute_url(self):
     #   return reverse('face:retrain', kwargs={'pk':self.pk})

class CattleLog(models.Model):
    NO = 'NO'
    YES = 'YES'
    A = ' 1-10 pts '
    B = '10-20 pts'
    C = '20-30 pts'
    D = '30-40 pts'
    E = '50-60 pts'
    F = '60-70 pts'
    G = '70-80 pts'
    H = '80-90 pts'
    I = '90-100 pts'
    LAC_CHOICES = (
        (NO, 'NO'),
        (YES, 'YES'),
    )
    PTS_CHOICES = (
        (A, ' 1-10 pts'),
        (B, '10-20 pts'),
        (C, '20-30 pts'),
        (D, '30-40 pts'),
        (E, '50-60 pts'),
        (F, '60-70 pts'),
        (G, '70-80 pts'),
        (G, '70-80 pts'),
        (H, '80-90 pts'),
        (I, '90-100 pts'),
    )
    cow = models.ForeignKey(Cow, on_delete=models.CASCADE)
    log = models.DateTimeField()
    birth_date = models.DateField()  # this must go in the cow model as it is a constant
    description = models.CharField(max_length=100000)

    lactating = models.CharField(max_length=15, choices=LAC_CHOICES,
        default=NO)
    feeding_scheme = models.CharField(max_length=100)
    condition_score = models.CharField(max_length=15, choices=PTS_CHOICES,
        default=A)
    injection_type = models.CharField(max_length=100)
    weight = models.PositiveSmallIntegerField(default=0)
    injection_Last_Date = models.DateTimeField()
    insemination_date = models.DateTimeField()

    def __str__(self):
        return 'last log date: '+str(self.log)


class CattleImage(models.Model):
    classify_img = models.FileField(default=None)
    def get_absolute_url(self):
        return reverse('face:detail', kwargs={'pk':self.pk})

dirtroad69/face/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import CattleImage

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class CattleImageForm(forms.ModelForm):

    class Meta:
        model = CattleImage
        fields = ['classify_img']


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

dirtroad69/face/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect,  get_object_or_404
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .models import Cow, CattleImage, CattleLog
from .forms import UserForm, UserLoginForm, CattleImageForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
import os
from skimage.transform import resize
from PIL import Image
import time
from datetime import timedelta
import numpy as np
from sklearn.externals import joblib
import tensorflow as tf

from django.db.models import Q
from .cfrs import getTransfer1

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
#PATH = 'C:/Users/Reg2017/PycharmProjects/JeffDropsIT/DirtRoad69'
PATH = 'C:/Users/Reg2017/Desktop/final_step/JeffDropsIT/DirtRoad69'
from PIL import Image
#im = Image.open(path)
data_dir = 'C:\\Users\\Reg2017\\PycharmProjects\\JeffDropsIT\\DirtRoad69\\face\\inception' # directory for inception model
path_graph_def = "classify_image_graph_def.pb" # inception model downloaded graph
label = np.array([ [1.,  0.,  0.]])  # label with one-hot encode
graph = tf.Graph()

# Set the new graph as the default.
with graph.as_default():

# TensorFlow graphs are saved to disk as so-called Protocol Buffers
# aka. proto-bufs which is a file-format that works on multiple
# platforms. In this case it is saved as a binary file.

# Open the graph-def file for binary reading.
        path = os.path.join(data_dir, path_graph_def)
        with tf.gfile.FastGFile(path, 'rb') as file:
             # The graph-def is a saved copy of a TensorFlow graph.
             # First we need to create an empty graph-def.
            graph_def = tf.GraphDef()

            # Then we load the proto-buf file into the graph-def.
            graph_def.ParseFromString(file.read())

                # Finally we import the graph-def to the default TensorFlow graph.
            tf.import_graph_def(graph_def, name='')
session = tf.Session(graph=graph)
print("graph created successfully")

def convert_2_1D_array(t_v_i, clf):
    for i in clf.predict(t_v_i):
        i
    return i

def get_index(array):
    count = 0
    for i in array:
        if i == 1:
            count = 0
        else:
            count += 1
    return count

def percentage(transfer_values_im, clf):
    item = np.array(clf.predict_proba(transfer_values_im))
    all_scores = []
    for i in item:
        score = i[0][1]
        all_scores.append(score)
    maximum = max(all_scores)
    return maximum


def useTensor(img):
    #graph, session = getTransfer.graphing()
    #session = getTransfer.tf.Session(graph=graph)
    # In[14]:
    transfer_layer = graph.get_tensor_by_name('pool_3:0')

    transfer_values_im, time_dif = getTransfer1.transfer_values(image=img)

    clf = inception_check_up()
    item = get_index(convert_2_1D_array(transfer_values_im, clf))
    acc = percentage(transfer_values_im, clf)
    x, y_true, y_pred_cls, sess = getTransfer1.restore()

    # In[65]:

    feed_dict = {x: transfer_values_im, y_true: getTransfer1.label}

    # In[66]:

    cls_pred = sess.run(y_pred_cls, feed_dict=feed_dict)


    # In[67]:

    return getTransfer1.getClass(cls_pred), float(acc), item, time_dif

def inception_check_up():
    #joblib.dump(clf, 'C:\\peri\\Decision_tree.pkl')
    clf_decision = joblib.load('C:\\peri_new1\\Decision_tree.pkl')
    print("Successful")
    return clf_decision

def retrain(request):
    if not request.user.is_authenticated():
        return render(request, 'face/login.html')
    else:
        return render(request, 'face/retrain.html')

def class_name(pk_temp):
    if pk_temp == 0:
        pk = 4
    elif pk_temp == 1:
        pk = 2
    elif pk_temp == 2:
        pk = 3
    return pk

def classification(request):
    if not request.user.is_authenticated():
        return render(request, 'face/login.html')
    else:
        form = CattleImageForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            cattleImage = form.save(commit=False)
            #cattleImage.user = request.user
            cattleImage.classify_img = request.FILES['classify_img']
            file_type = cattleImage.classify_img.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'cattleImage': cattleImage,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'face/classify.html', context)
            cattleImage.save()
            img = CattleImage.objects.last()
            path = PATH + img.classify_img.url

            img = Image.open(path)
            img = img.resize((200, 200), Image.ANTIALIAS)
            #img.get_absolute_url()


            pk_temp, acc, item, time_taken = useTensor(img=img)
            img = CattleImage.objects.last()
            print(pk_temp)
            pk = class_name(pk_temp)
            item = class_name(pk_temp)
            #else:
               # error_message = "There system failed to classify the image provided please use other methods to classify the cow"
                #pk=2
            cow = get_object_or_404(Cow, pk=pk)
            return render(request, 'face/detail.html', {'cow': cow,
                                                        'img': img,
                                                        'acc': '%.1f' % (acc*100),
                                                        'item': get_object_or_404(Cow, pk=item),
                                                        'error_message': 'Uploaded Image',
                                                        'time_taken': str(round(time_taken,2))+str(' sec')

                                                        })
        context = {
            "form": form,
        }
        return render(request, 'face/classify.html', context)





class IndexView(generic.ListView):
    template_name = 'face/index.html'
    login_url = 'face/login.html'
    context_object_name = 'all_cows'

    def get_queryset(self):
        result = Cow.objects.all()

        query = self.request.GET.get('q')
        if query:
            result = result.filter(
                Q(name__icontains=query) |
                Q(breed__icontains=query) |
                Q(gender__icontains=query)
            ).distinct()

        return result


class DetailView(generic.DetailView):
    model = Cow

    template_name = 'face/detail.html'


class CowCreate(CreateView):
    model = CattleLog
    fields = ['log','lactating','feeding_scheme','condition_score', 'injection_type', 'weight', 'injection_Last_Date', 'insemination_date' ]


class CowUpdate(UpdateView):
    model = CattleLog
    fields = ['log','lactating','feeding_scheme','condition_score', 'injection_type', 'weight', 'injection_Last_Date', 'insemination_date' ]


class CowDelete(DeleteView):
    model = Cow
    success_url = reverse_lazy('face:index')


#class ClassifyView(CreateView):
  #  model = CattleImage
  #  login_url = 'face/login.html'
  #  fields = ['classify_img']
   # template_name = 'face/classify.html'

class UserFormView(View):
    form_class = UserForm
    template_name = 'face/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (nomarlized_data)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #authenticate user
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('face:index')
        return render(request, self.template_name, {'form': form})     # try again


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'face/index.html')
            else:
                return render(request, 'face/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'face/login.html', {'error_message': 'Invalid login'})
    return render(request, 'face/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'face/login.html', context)

dirtroad69/face/templates/face/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Smart Farm{% endblock %}</title>
    {% load staticfiles %}
    <link rel="icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'face/style.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>



</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#TopNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'face:index' %}">SmartFarm</a>
        </div>

         <!-- Items -->
        <div class="collapse navbar-collapse" id="TopNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block cattle_active %} {% endblock %}">
                        <a href="{% url 'face:index' %}">
                        <span class="" aria-hidden="true"></span>&nbsp;All Cattle
                    </a>
                      <li class="{% block classify_active %} {% endblock %}">
                        <a href="{% url 'face:classify' %}">
                        <span class="" aria-hidden="true"></span>&nbsp;Classify Cattle
                    </a>
                    </li>
                </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'face:index' %}">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    <div class="input-group-btn">
						<button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
				    </div>
				</div>
                <!-- <button type="submit" class="btn btn-default">Search</button> -->
            </form>


                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block retrain_active %}{% endblock %}">
                    <a href="{% url 'face:retrain' %}">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp; Retrain
                    </a>
                    </li>
                    <li>
                    <a href="{% url 'face:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                    </li>
                    <li class="">
                        <a href="{{ pk }}/admin/face/cattlelog/add/">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Log
                    </a>
                      <li class="">
                        <a href="/admin/">
                        <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>Admin
                    </a>
                    </li>
                </ul>
        </div>



    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

dirtroad69/face/templates/face/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SmartFarm{% endblock %}</title>
    {% load staticfiles %}
    <link rel="icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'face/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">SmartFarm</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'face:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'face:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

dirtroad69/face/templates/face/cattlelog_form.html
{% extends 'face/base.html' %}
{% block title %}Add a New Cow{% endblock %}
{% block cattle_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-12 col-md-37">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'face/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>
                        </div>


                    </form>

                </div>
            </div>
        </div>



    </div>

</div>

{% endblock %}

dirtroad69/face/templates/face/classify.html
{% extends 'face/base.html' %}
{% block title %}Get Cattle Information{% endblock %}
{% block classify_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-12 col-md-37">
            <div class="panel panel-default">
                <div class="col-lg-6 col-centered">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'face/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>
                        </div>


                    </form>

                </div>
            </div>
        </div>


           <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is to classify?</h3>
                    <p>Classifying is a functionality that allows you to upload an image using your mobile device to the cloud, with the aim to aid in determining the identity of your of livestock using Computer vision .</p>
                    <h3>How do I Classify?</h3>
                    <p>Firstly, upload an image by taking a photo of the livestock you wish to identify preferably in a distance no farther than one meter. Once the photo has been taken you will be able to add/upload them by pressing submit.</p>
                    <h3>What are some classifying best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image format such as .JPG only</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Portrait view images work best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

dirtroad69/face/templates/face/detail.html
{% extends 'face/base.html' %}
{% block title %}Cow Detail{% endblock %}


{% block body %}
    <div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'face:detail' cow.id %}">
                        {% if cow.cow_img %}
                            <img src="{{ cow.cow_img.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ cow.name }} <small>{{ cow.gender }}</small></h1>
                    <h1>Breed: {{ cow.breed }}</h1>
                    {% if error_message %}<h3> <small>{{error_message}} </small></h3> {% endif %}
                    <img src="{{ img.classify_img.url }}" class="img-responsive">
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'face:index'%}">View All</a></li>
                <li role="presentation"><a href="{{ pk }}/admin/face/cattlelog/add/">Add New Log</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Logs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Log Date</th>
                            <th>Lactate Status</th>
                            <th>condition score</th>
                            <th>feeding scheme</th>
                            <th>injection type</th>
                            <th>weight</th>
                            <th>injection Last Date</th>
                            <th>insemination date</th>


                        </tr>
                        </thead>
                        <tbody>
                        {% for log in cow.cattlelog_set.all %}
                            <tr>
                                <td>{{ log.log }}</td>
                                <td>
                                   <p>{{ log.lactating }}</p>
                                </td>
                                <td>
                                    <p>{{ log.condition_score }}</p>
                                </td>
                                <td>
                                    <p>{{ log.feeding_scheme }}</p>
                                </td>
                                <td>
                                    <p>{{ log.injection_type }}</p>
                                </td>
                                <td>
                                    <p>{{ log.weight }} kg</p>
                                </td>
                                <td>
                                    <p>{{ log.injection_Last_Date }}</p>
                                </td>
                                <td>
                                    <p>{{ log.insemination_date }}</p>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            {% if error_message %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 >Model Comparison</h2>
                  <p >Click on the button to toggle between showing and hiding Model Comparison results.</p>
                  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">See results</button>

                  <div id="demo" class="collapse">
                        <div class="col-sm-20 col-md-9">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <h3>What is Model Comparison?</h3>
                                        <p>Model Comparison is a functionality that allows you to evaluate the performance of a different Algorithm in the livestock recognition system.</p>
                                        <h3>How does it work?</h3>
                                        <p>A different Algorithms is used to classify the image that you upload namely Decision Tree analysis. The accuracy and the image of the predicted cow is returned for the algorithm.</p>
                                        <h3>The Model Comparison test Results!</h3>
                                        <p>            Decision tree</p>
                                    <ul>
                                        <li><H4>Accuracy: {{ acc }}</H4></li>
                                        <li><H4>Evaluation Time : {{ time_taken }}</H4></li>
                                        <li><h4>Image Prediction</h4><img src="{{ item.cow_img.url }}" style="max-height: 100px; max-width: 100px;" class="img-responsive"></li>
                                    </ul>
                                    </div>
                                </div>
                        </div>
                  </div>

                </div>
            </div>
            {% endif %}

        </div>

    </div>

</div>


{% endblock %}

dirtroad69/face/templates/face/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field  }}</div>
    </div>

{% endfor %}

dirtroad69/face/templates/face/login.html
{% extends 'face/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'face:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'face:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}